---

- name: Install elastic
  hosts: elasticsearch
  become: yes

  tasks:



  - name: Get elastic
    ansible.builtin.get_url:
      url: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/e/elasticsearch/elasticsearch-7.17.9-amd64.deb
      dest: /home/admin/

  - name: Install elastic
    apt:
      deb: /home/admin/elasticsearch-7.17.9-amd64.deb

  - name: Systemctl daemon reload
    systemd:
      daemon_reload: true
      name: elasticsearch.service
      state: started

  - name: Copy conf-file
    copy:
      src: ./static/elasticsearch.yml
      dest: /etc/elasticsearch/elasticsearch.yml
      mode: 0644
      owner: root
      group: elasticsearch

  - name: Restart elastic
    systemd:
      name: elasticsearch.service
      state: restarted





