---
- name: Install and configure Nginx
  hosts: web
  become: true

  tasks:
  
    - name: Install Nginx
      apt:
        update_cache: yes
        name: nginx
        state: present

    - name: Change main page
      ansible.builtin.copy:
        src: ./static/index.html
        dest: /var/www/html/index.html
        owner: admin
        group: sudo
        mode: '0644'

    - name: Enable Nginx service
      systemd:
        name: nginx
        enabled: yes
