---
- name: Zabbix server
  hosts: zabbix-server
  become: yes

  tasks:

  - name: install prerequisites
    become: yes
    apt: name={{ item }} state=latest
    with_items:
      - libpq-dev
      - python3-psycopg2
      - postgresql
    tags:
      - packages

  - name: Repo
    get_url:
      url: 'https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-5+debian12_all.deb'
      dest: '/home/admin/zabbix-release_6.0-5+debian12_all.deb'

  - name: Dpkg zabbix
    apt:  
      deb: '/home/admin/zabbix-release_6.0-5+debian12_all.deb'

  - name: Update 
    apt:
      update_cache: yes
      
  - name: Install server
    apt:  
      name: zabbix-server-pgsql
      state: present   

  - name: Install frontend
    apt:  
      name: zabbix-frontend-php
      state: present   
      
  - name: PHP
    apt:  
      name: php8.2-pgsql
      state: present         
      
  - name: Install apache
    apt:  
      name: apache2
      state: present   
      
  - name: Install zabbix-apach-conf
    apt:  
      name: zabbix-apache-conf
      state: present

  - name: Install zabbix-sql
    apt:  
      name: zabbix-sql-scripts
      state: present      
      
  - name: Install zabbix-agent
    apt:  
      name: zabbix-agent
      state: present


  - name: Create zabbix user
    postgresql_user:
      name: zabbix
      password: zabbix
      role_attr_flags: SUPERUSER
      #login_host: localhost

  - name: Extract server.sql
    become: yes
    ansible.builtin.shell:
      cmd:  zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz > ~/server.sql 
 
  - name: Import server.sql
    community.postgresql.postgresql_db:
      name: zabbix
      state: restore
      target: ~/server.sql

  - name: config
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_server.conf
      insertafter: "DBPassword="
      line: DBPassword=zabbix

  - name: enable and restart zabbix and webserver
    ansible.builtin.systemd:
     name: zabbix-server
     enabled: true
     state: restarted

  - name: enable and restart zabbix agent
    ansible.builtin.systemd:
      name: zabbix-agent
      enabled: true
      masked: no
      state: restarted
      
  - name: enable and restart apache2
    ansible.builtin.systemd:
      name: apache2
      enabled: true
      masked: no
      state: restarted